<?php

$__rpdir = realpath(__DIR__ . '/../');

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        $__rpdir . '/app/Providers/AppServiceProvider.php',
        $__rpdir . '/app/Providers/BusServiceProvider.php',
        $__rpdir . '/app/Providers/ConfigServiceProvider.php',
        $__rpdir . '/app/Providers/EventServiceProvider.php',
        $__rpdir . '/app/Providers/RouteServiceProvider.php',
        $__rpdir . '/app/Http/Controllers/RestController.php',
        $__rpdir . '/app/Http/Controllers/SplashController.php',
        $__rpdir . '/app/Http/Controllers/StorageController.php',
        $__rpdir . '/app/Http/Middleware/AccessCheck.php',
        $__rpdir . '/app/Http/Middleware/Cors.php',
        $__rpdir . '/app/Http/Middleware/FirstUserCheck.php',
        $__rpdir . '/app/Http/Middleware/Limits.php',
        $__rpdir . '/app/Http/Middleware/DataCollection.php',
        $__rpdir . '/vendor/dreamfactory/df-managed/src/Providers/BluemixServiceProvider.php',
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
